apiVersion: v1
kind: Pod
metadata:
        name: 5gmeta-license-pod
        namespace: <namespace>
spec:
        containers:
                - name: license-api
                  image: 5gmeta/license-api:1.0
                  ports:
                          - containerPort: 5000
                - name: license-db
                  image: mongo:latest
        imagePullSecrets:
                - name: regcred
